tms_rp/tms_rp_action/src/tms_rp_rp.cpp, tms_ss/tms_ss_vicon/src/vicon_stream.cpp
add new robot kxp(2006) to vicon stream
=> add robot kxp

tms_rp/tms_rp_viewer/src/tms_rp_viewer_bar.cpp
=> modify kxp's viewer program

tms_rc/tms_rc_katana/src/roskatana_test1.cpp, tms_rc/tms_rc_kxp/kxp_virtual_control/src/kxp_virtual_control.cpp, tms_rc/tms_rc_pioneer/src/test1_move.cpp, tms_rp/tms_models/robot/KXP/KXP.yaml, tms_rp/tms_rp_action/include/tms_rp_rp.h, tms_rp/tms_rp_action/src/tms_rp_rp.cpp
RC_katana
- modify gripper value
RC_pioneer
- add set odom function with vicon system
RP
- modify move, grasp, give function for kxp(ID=2006)
=> modify subtask programs for kxp's task

tms_rc/tms_rc_katana/src/roskatana_test1.cpp
=> update file path

tms_rp/tms_rp_action/src/tms_rp_rp.cpp, tms_ss/tms_ss_vicon/src/vicon_stream.cpp
- add kobuki to vicon system
- modify sensing subtask
=> add kobuki to vicon system and modify sensing subtask

tms_rp/tms_rp_viewer/src/tms_rp_viewer_bar.cpp
=> modify ss program for kobuki

tms_rc/tms_rc_kobuki/kobuki_control/CMakeLists.txt, tms_rc/tms_rc_kobuki/kobuki_control/include/kobuki_control/kobuki_control.h, tms_rc/tms_rc_kobuki/kobuki_control/package.xml, tms_rc/tms_rc_kobuki/kobuki_control/src/kobuki_control.cpp, tms_rc/tms_rc_kobuki/kobuki_virtual_control/src/kobuki_virtual_control.cpp
add new package for actual_kobuki
=> add new package for actual_kobuki

tms_rp/tms_rp_action/include/tms_rp_rp.h, tms_rp/tms_rp_action/src/tms_rp_rp.cpp
add new service for actual kobuki moving
=> modify to move kobuki lines

tms_rc/tms_rc_kobuki/kobuki_control/src/kobuki_control.cpp
fix service name
vicon's rotate unit <- degree
=> fix service name

tms_rc/tms_rc_kobuki/kobuki_control/src/kobuki_control.cpp, tms_rp/tms_rp_action/src/tms_rp_rp.cpp
modify kobuki driver 
- fix a bug
modify rp to fit
- create actual_kobuki move
=> modify kobuki driver and rp to fit

tms_rc/tms_rc_kobuki/kobuki_control/src/kobuki_control.cpp
<rotate+>
-				if ((-180-ini_ori_th <= var_ori_th && var_ori_th < goal_ang-360)
-						|| (0 <= var_ori_th && var_ori_th <= 180-goal_ang)) {
+				if ((ini_ori_th <= var_ori_th && var_ori_th <= 180)
+						|| (-180 <= var_ori_th && var_ori_th < goal_ang)) {
<rotate->
-				if ((-180-ini_ori_th <= var_ori_th && var_ori_th <= 0)
-						|| (goal_ang+360 < var_ori_th && var_ori_th <= 180-ini_ori_th)) {
+				if ((-180 <= var_ori_th && var_ori_th <= ini_ori_th)
+						|| (goal_ang < var_ori_th && var_ori_th <= 180)) {
=> modify judging function for rotate kobuki

tms_rc/tms_rc_katana/src/roskatana_test1.cpp, tms_rc/tms_rc_pioneer/src/test1_move.cpp
change move_katana_array algorithm
=> modify KXP driver

tms_rc/tms_rc_kobuki/kobuki_control/src/kobuki_control.cpp, tms_rp/tms_rp_action/src/tms_rp_rp.cpp, tms_ss/tms_ss_ods/ods_person_detection/src/ods_realtime_persondt.cpp
kobuki_control
- round off vicon data to one decimal place
rp_rp
- use kobuki move linear abs function
- change final judgement
ods_realtime_persondt.cpp
- change subscribe topic
=> modify 3 programs for patrol task

tms_ss/tms_ss_ods/ods_person_detection/src/ods_realtime_persondt.cpp
=> change using service

tms_rc/tms_rc_pioneer/src/test1_move.cpp
- initialize Robot's odometry using vicon data
- modify return timing
=> modify initialization

tms_rc/tms_rc_pioneer/src/test1_move.cpp, tms_rp/tms_rp_action/include/tms_rp_pp.h, tms_rp/tms_rp_action/src/tms_rp_pp.cpp
pioneer
- fix a bug
path plan
- use the same map data in voronoiPathPlanner function
=> modify path planning

tms_ss/tms_ss_xtion/CMakeLists.txt, tms_ss/tms_ss_xtion/include/DepthImageMaker.h, tms_ss/tms_ss_xtion/include/MyCalibration.h, tms_ss/tms_ss_xtion/include/OpenNIDeviceListener.hpp, tms_ss/tms_ss_xtion/include/myutility.h, tms_ss/tms_ss_xtion/package.xml, tms_ss/tms_ss_xtion/src/DepthImageMaker.cpp, tms_ss/tms_ss_xtion/src/MyCalibration.cpp, tms_ss/tms_ss_xtion/src/main.cpp, tms_ss/tms_ss_xtion/src/myutility.cpp
<p>
Add tms_ss_xtion and pushed.
</p>
=> issue333: add tms_ss_xtion

tms_ss/tms_ss_xtion/CMakeLists.txt, tms_ss/tms_ss_xtion/estimateExtrinsicParameters/include/MyCalibration.h, tms_ss/tms_ss_xtion/estimateExtrinsicParameters/src/MyCalibration.cpp, tms_ss/tms_ss_xtion/estimateExtrinsicParameters/src/main.cpp, tms_ss/tms_ss_xtion/package.xml
<p>
I fix bugs about build dependency and add a few changes.
But other changes are very small enough to ignore.
</p>
=> tms_ss_xtion: fix CMakeLists.txt and package.xml

tms_rp/bsen_description/launch/environment.launch, tms_rp/bsen_description/urdf/bsen.urdf
=> added joint_state_publisher for control of wagon using vicon data

tms_db/tms_db_state_publisher/CMakeLists.txt, tms_db/tms_db_state_publisher/package.xml, tms_db/tms_db_state_publisher/src/tms_db_state_publisher.cpp
re-positioning of moveable objects like wagon using vicon system
=> added a feature for re-positioning of moveable objects like wagon

tms_ss/tms_ss_pot/launch/pot_urg.launch
Sorry. I forgot launch file.
so rewrite, yes.
=> Alse rewrite launch file(I fotgot)

tms_rp/smartpal5_moveit_config/.setup_assistant, tms_rp/smartpal5_moveit_config/CMakeLists.txt, tms_rp/smartpal5_moveit_config/config/fake_controllers.yaml, tms_rp/smartpal5_moveit_config/config/joint_limits.yaml, tms_rp/smartpal5_moveit_config/config/kinematics.yaml, tms_rp/smartpal5_moveit_config/config/ompl_planning.yaml, tms_rp/smartpal5_moveit_config/config/smartpal5.srdf, tms_rp/smartpal5_moveit_config/launch/default_warehouse_db.launch, tms_rp/smartpal5_moveit_config/launch/demo.launch, tms_rp/smartpal5_moveit_config/launch/fake_moveit_controller_manager.launch.xml, tms_rp/smartpal5_moveit_config/launch/joystick_control.launch, tms_rp/smartpal5_moveit_config/launch/move_group.launch, tms_rp/smartpal5_moveit_config/launch/moveit.rviz, tms_rp/smartpal5_moveit_config/launch/moveit_rviz.launch, tms_rp/smartpal5_moveit_config/launch/ompl_planning_pipeline.launch.xml, tms_rp/smartpal5_moveit_config/launch/planning_context.launch, tms_rp/smartpal5_moveit_config/launch/planning_pipeline.launch.xml, tms_rp/smartpal5_moveit_config/launch/run_benchmark_ompl.launch, tms_rp/smartpal5_moveit_config/launch/sensor_manager.launch.xml, tms_rp/smartpal5_moveit_config/launch/setup_assistant.launch, tms_rp/smartpal5_moveit_config/launch/smartpal5_moveit_controller_manager.launch.xml, tms_rp/smartpal5_moveit_config/launch/smartpal5_moveit_sensor_manager.launch.xml, tms_rp/smartpal5_moveit_config/launch/trajectory_execution.launch.xml, tms_rp/smartpal5_moveit_config/launch/warehouse.launch, tms_rp/smartpal5_moveit_config/launch/warehouse_settings.launch.xml, tms_rp/smartpal5_moveit_config/package.xml
+ moveit_config package for SmartPal5 base on URDF of SmartPal
=> added moveit_config pck for SmartPal5

tms_rc/tms_rc_pot/CMakeLists.txt, tms_rc/tms_rc_pot/package.xml, tms_rc/tms_rc_pot/src/tf_test.cpp, tms_rc/tms_rc_pot/src/virtual_pot_robot.cpp
first 
1. tf_test.cpp
2. virtual_robot_control.cpp
in this package
if you publish robot polot and scan data to tf_test , you can test slam easily.
you can.
=> new robot control package for portable : tms_rc_pot

tms_rp/tms_rp_voronoi_map/CMakeLists.txt, tms_rp/tms_rp_voronoi_map/package.xml, tms_rp/tms_rp_voronoi_map/src/voronoi_map.cpp
=> added new package for voronoi map

tms_rp/tms_rp_voronoi_map/CMakeLists.txt, tms_rp/tms_rp_voronoi_map/package.xml, tms_rp/tms_rp_voronoi_map/src/voronoi_map.cpp
=> add viewer for voronoi map in RViz

tms_db/tms_db_state_publisher/src/tms_db_state_publisher.cpp, tms_rc/smartpal5_description/urdf/smartpal5.urdf.xacro, tms_rc/smartpal5_description/urdf/smartpal5_gazebo.urdf.xacro, tms_rp/rostms_description/launch/all_components.launch, tms_rp/rostms_description/launch/environments.launch, tms_rp/rostms_description/launch/objects.launch, tms_rp/rostms_description/launch/robots.launch, tms_rp/rostms_description/urdf/all_components.urdf.xacro, tms_rp/rostms_description/urdf/objects.urdf.xacro, tms_rp/rostms_description/urdf/robots.urdf.xacro, tms_rp/rostms_description/urdf/robots_gazebo.urdf.xacro, tms_rp/rostms_description/urdf/robots_standalone.urdf.xacro
roslaunch rostms_description all_components.launch --screen
roslaunch rostms_description environments.launch --screen
roslaunch rostms_description objects.launch --screen 
roslaunch rostms_description robots.launch --screen
=> added 4 pattern models configuration

tms_rp/tms_rp_path_planning/src/path_planning.cpp
```sh
roslaunch rostms_description all_components.launch --screen
rosrun tms_rp_voronoi_map tms_rp_voronoi_map
rosrun tms_rp_path_planning tms_rp_path_planning
rosservice call /rps_voronoi_path_planning "robot_id: 2003
start_pos: {x: 2000.0, y: 4000.0, z: 0.0, th: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
goal_pos: {x: 13000.0, y: 1000.0, z: 0.0, th: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}"
```
=> added shadow path for smartpal5

dependency/install_dependencies_pkg.sh
=> added dependencies option to use the moveit in ROS-TMS

tms_rp/smartpal5_moveit_config/.setup_assistant, tms_rp/smartpal5_moveit_config/config/fake_controllers.yaml, tms_rp/smartpal5_moveit_config/config/joint_limits.yaml, tms_rp/smartpal5_moveit_config/config/kinematics.yaml, tms_rp/smartpal5_moveit_config/config/ompl_planning.yaml, tms_rp/smartpal5_moveit_config/config/smartpal5.srdf
=> added right arm for smartpal5_moveit_config function

tms_rp/rostms_description/urdf/environments.urdf.xacro
I have changed wordrobe & workdesk & kitchen model position on the rviz.
no change on gazebo
=> change wordrobe & workdesk & kitchen model position on the rviz

tms_ss/tms_ss_vicon/package.xml, tms_ss/tms_ss_vicon/src/vicon_stream.cpp
=> changed the unit used in tms_ss_vicon package of ros-tms system

tms_rp/tms_rp_path_planning/package.xml, tms_rp/tms_rp_path_planning/src/path_planning.cpp, tms_rp/tms_rp_voronoi_map/package.xml, tms_rp/tms_rp_voronoi_map/src/voronoi_map.cpp
=> change the unit used in voronoi map nodes of ros-tms

tms_rp/rostms_description/launch/environments.launch, tms_rp/rostms_description/launch/objects.launch, tms_rp/rostms_description/launch/robots.launch, tms_rp/rostms_description/urdf/robots_standalone.urdf.xacro
roslaunch rostms_description environments.launch --screen
roslaunch rostms_description objects.launch --screen 
roslaunch rostms_description robots.launch --screen 
roslaunch rostms_description all_components.launch --screen
=> We can call the models like environments, objects and robots

tms_rp/rostms_description/launch/all_components_with_moveit.launch, tms_rp/rostms_description/urdf/all_components_with_moveit.urdf.xacro
=> added launch file to open the environment with robot and moveit

tms_rp/rostms_bringup/launch/moveit.launch, tms_rp/rostms_bringup/launch/rostms.launch, tms_rp/rostms_description/launch/all_components_without_robots.launch, tms_rp/rostms_description/rviz_config/rviz_config.rviz, tms_rp/smartpal5_moveit_config/config/smartpal5.srdf, tms_rp/smartpal5_moveit_config/launch/demo.launch
I modified the scripts of rostms_bringup.
+ roslaunch rostms_bringup rostms.launch (view the environment of b-sen room using RViz)
+ roslaunch rostms_bringup moveit.launch (use the moveit API using moveit plugin of RViz)
I abandon a plan to use both viewer and moveit plugin, because collision method of moveit was very slow when using all mesh models of environment, object and robot. So, I will use the RViz as separate windows.
You can check the commands of our system below wiki page.
https://github.com/irvs/ros_tms/wiki/commands
=> modified the scripts of rostms_bringup

tms_db/tms_db_manager/scripts/tms_db_publisher.py, tms_db/tms_db_manager/scripts/tms_db_writer.py, tms_db/tms_db_manager/src/tms_db_manager/tms_db_util.py
=> added tms_db_publisher node to publish the current information of DB

tms_ts/tms_ts_subtask/CMakeLists.txt, tms_ts/tms_ts_subtask/include/tms_ts_subtask/tms_ts_subtask.h, tms_ts/tms_ts_subtask/src/tms_ts_subtask.cpp
```sh
roscore
roslaunch tms_db_manager tms_db_manager.launch --screen
roslaunch rostms_bringup rostms.launch
rosrun tms_rp_voronoi_map tms_rp_voronoi_map
rosrun tms_rp_path_planning tms_rp_path_planning
```
```sh
rosrun tms_ts_ts ts_master
rosrun tms_ts_subtask tms_ts_subtask 
rosrun smach_viewer smach_viewer.py
```
```sh
rosservice call /tms_ts_master "{rostime: 0, task_id: 8005, robot_id: 2003, object_id: 7001, user_id: 0, place_id: 5001, priority: 0}"
```
=> added new node tms_ts_subtask for task scheduler

tms_db/tms_db_manager/scripts/tms_db_reader.py, tms_ts/tms_ts_smach/scripts/2015914_171017.py, tms_ts/tms_ts_subtask/src/tms_ts_subtask.cpp
```sh
roscore
roslaunch tms_db_manager tms_db_manager.launch --screen
roslaunch rostms_bringup rostms.launch
roslaunch rostms_bringup moveit.launch
rosrun tms_rp_voronoi_map tms_rp_voronoi_map
rosrun tms_rp_path_planning tms_rp_path_planning
rosrun tms_ts_ts ts_master
rosrun tms_ts_subtask tms_ts_subtask 
rosrun smach_viewer smach_viewer.py
```
```sh
rosservice call /tms_ts_master "{rostime: 0, task_id: 8005, robot_id: 2003, object_id: 6015, user_id: 0, place_id: 0, priority: 0}"
```
=> modified the query of tms_ts for new system

tms_db/tms_db_manager/scripts/tms_db_backuper.py, tms_db/tms_db_manager/scripts/tms_db_publisher.py, tms_db/tms_db_manager/scripts/tms_db_reader.py, tms_db/tms_db_manager/scripts/tms_db_writer.py
id, history_data, backup_data, data_person, data_robot, data_sensor, data_structure, data_space, data_furniture, data_object, data_task, data_subtask, data_state
default, now, history, backup
=> modified the nodes of tms_db_manager for task scheduler

tms_rp/tms_rp_path_planning/src/path_planning.cpp, tms_rp/tms_rp_voronoi_map/launch/voronoi.launch, tms_ts/tms_ts_subtask/src/tms_ts_subtask.cpp, tms_ts/tms_ts_ts/launch/task_scheduler.launch
- modified tms_rp and tms_ts for task scheduler
- added a task_scheduler.launch
- added a voronoi.launch
=> modified tms_rp and tms_ts for task scheduler

tms_rc/tms_rc_smartpal/smartpal_virtual_control/src/smartpal5_virtual_control.cpp, tms_ts/tms_ts_subtask/src/tms_ts_subtask.cpp, tms_ts/tms_ts_ts/src/tms_ts_nodelet.cpp, tms_ts/tms_ts_ts/src/ts_master.cpp
- modified the nodes related tms_ts for task scheduler
- changed the unit of virtual controller of smartpal5
[![Demo Video](https://j.gifs.com/y4wp4l.gif)](https://youtu.be/9lbuLAD1c_4)
=> Integration for task scheduler

tms_rp/smartpal5_arm_navigation/scripts/subtask_grasp.py
=> changed the subtask_grasp for ts

tms_rc/tms_rc_smartpal/smartpal_virtual_control/src/smartpal5_virtual_control.cpp, tms_rp/smartpal5_arm_navigation/scripts/subtask_grasp.py, tms_ts/tms_ts_subtask/include/tms_ts_subtask/tms_ts_subtask.h, tms_ts/tms_ts_subtask/src/tms_ts_subtask.cpp
```sh
roscore
roslaunch tms_db_manager tms_db_manager.launch --screen
roslaunch rostms_bringup rostms_with_moveit.launch
roslaunch tms_rp_voronoi_map voronoi.launch --screen
roslaunch tms_ts_ts task_scheduler.launch --screen
rosrun tms_rc_smartpal_virtual_control smartpal_virtual_control
rosrun smartpal5_arm_navigation subtask_grasp.py
```
```sh
rosservice call /tms_ts_master "{rostime: 0, task_id: 8001, robot_id: 2003, object_id: 7001, user_id: 0, place_id: 0, priority: 0}"
```
https://youtu.be/oy1HlT8fh3w
=> added a subtask_grasp service for task scheduler

tms_rp/skeleton_description/CMakeLists.txt, tms_rp/skeleton_description/box_state_publisher/main.cpp, tms_rp/skeleton_description/calc_joint_angles/for_model01.h, tms_rp/skeleton_description/kinect_state_publisher/main.cpp, tms_rp/skeleton_description/skeleton_state_publisher/main.cpp, tms_ss/tms_ss_kinect_v2/CMakeLists.txt, tms_ss/tms_ss_kinect_v2/scripts/skeleton_stream.py, tms_ss/tms_ss_kinect_v2/skeleton_integrator/main.cpp, tms_ss/tms_ss_kinect_v2/skeleton_viewer/main.cpp
I removed build errors. Please check it.
=> tms_ss_kinect_v2: fix build errors
